### ISSUE TITLE
Trouble with setup on Windows

### ISSUE THREAD

**Issue by darrengeary** [MicroPyramid/opensource-job-portal#117]
(env) λ python manage.py update_index
Traceback (most recent call last):
  File "c:\peeljobs\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "c:\peeljobs\env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "c:\peeljobs\env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "c:\peeljobs\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\peeljobs\env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "c:\peeljobs\env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\peeljobs\env\lib\site-packages\django_ses\__init__.py", line 6, in <module>
    from django_ses import settings
  File "c:\peeljobs\env\lib\site-packages\django_ses\settings.py", line 19, in <module>
    'https://' + AWS_SES_REGION_ENDPOINT)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by datatalking** [comment]
I'm experiencing the same error "AWS_SES_REGION_ENDPOINT" when setting up in AWS cloud.

**Comment by raidu4u** [comment]
@darrengeary you need to add AWS_SES_REGION_ENDPOINT value, it shouldn't be empty.

**Comment by abtpltd** [comment]
can we run it without aws
