### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [MicroPyramid/opensource-job-portal#70]
Hello,

I am running Ubuntu 18.04. I am attempting to install using the following instructions:
https://opensource-job-portal.readthedocs.io/en/latest/setup/index.html

I am at step 11. 
python3 manage.py migrate

I get the following output:

python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/classified/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/classified/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/classified/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/classified/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/classified/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/classified/peeljobs/jobsp/settings_local.py", line 1, in <module>
    from .settings import *
  File "/home/classified/peeljobs/jobsp/settings.py", line 358, in <module>
    MONGO_PORT = int(os.getenv("MONGO_PORT"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

I get the same problem regardless of if it's in an virtual env or not.

Any suggestions?

**Comment by gustawdaniel** [comment]
I have the following problem after `compose up`

```
daniel@daniel-Inspiron-3543:~/exp/job$ docker-compose up
Building webapp
Step 1/2 : from django
latest: Pulling from library/django
75a822cd7888: Pull complete
e4665cede9d1: Pull complete
202a45aa091c: Pull complete
7799136eb561: Pull complete
7a7f9ca3fd40: Pull complete
412f2d081014: Pull complete
Digest: sha256:5bfd3f442952463f5bc97188b7f43cfcd6c2f631a017ee2a6fca3cb8992501e8
Status: Downloaded newer image for django:latest
 ---> eb40dcf64078
Step 2/2 : copy entrypoint.sh /home/entrypoint.sh
 ---> 47f308528e17
Successfully built 47f308528e17
Successfully tagged job_webapp:latest
WARNING: Image for service webapp was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating job_webapp_1 ... done
Attaching to job_webapp_1
webapp_1  | CHANGELOG
webapp_1  | CONTRIBUTING.md
webapp_1  | Dockerfile
webapp_1  | LICENSE
webapp_1  | MANIFEST.in
webapp_1  | README.md
webapp_1  | agency
webapp_1  | candidate
webapp_1  | dashboard
webapp_1  | docker-compose.yml
webapp_1  | dockerfile_dj
webapp_1  | docs
webapp_1  | entrypoint.sh
webapp_1  | features
webapp_1  | install.txt
webapp_1  | jobsp
webapp_1  | manage.py
webapp_1  | manage_server.py
webapp_1  | mpcomp
webapp_1  | peeldb
webapp_1  | pjob
webapp_1  | psite
webapp_1  | recruiter
webapp_1  | requirements.txt
webapp_1  | search
webapp_1  | setup.py
webapp_1  | social
webapp_1  | static
webapp_1  | templates
webapp_1  | tickets
webapp_1  | Collecting Django==2.2.10 (from -r /home/peeljobs/requirements.txt (line 1))
webapp_1  |   Could not find a version that satisfies the requirement Django==2.2.10 (from -r /home/peeljobs/requirements.txt (line 1)) (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29, 2.0a1, 2.0b1, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.12, 2.0.13)
webapp_1  | No matching distribution found for Django==2.2.10 (from -r /home/peeljobs/requirements.txt (line 1))
webapp_1  | You are using pip version 9.0.1, however version 20.0.2 is available.
webapp_1  | You should consider upgrading via the 'pip install --upgrade pip' command.
webapp_1  | Traceback (most recent call last):
webapp_1  |   File "/home/peeljobs/manage.py", line 22, in <module>
webapp_1  |     execute_from_command_line(sys.argv)
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
webapp_1  |     utility.execute()
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 316, in execute
webapp_1  |     settings.INSTALLED_APPS
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 53, in __getattr__
webapp_1  |     self._setup(name)
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
webapp_1  |     self._wrapped = Settings(settings_module)
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 97, in __init__
webapp_1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
webapp_1  |   File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
webapp_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webapp_1  |   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
webapp_1  |   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
webapp_1  |   File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
webapp_1  |   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
webapp_1  |   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
webapp_1  |   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
webapp_1  |   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
webapp_1  |   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
webapp_1  |   File "<frozen importlib._bootstrap>", line 1129, in _exec
webapp_1  |   File "<frozen importlib._bootstrap>", line 1471, in exec_module
webapp_1  |   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
webapp_1  |   File "/home/peeljobs/jobsp/__init__.py", line 5, in <module>
webapp_1  |     from .celery import app as celery_app
webapp_1  |   File "/home/peeljobs/jobsp/celery.py", line 3, in <module>
webapp_1  |     from celery import Celery
webapp_1  | ImportError: No module named 'celery'
webapp_1  | Traceback (most recent call last):
webapp_1  |   File "/home/peeljobs/manage.py", line 22, in <module>
webapp_1  |     execute_from_command_line(sys.argv)
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
webapp_1  |     utility.execute()
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 316, in execute
webapp_1  |     settings.INSTALLED_APPS
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 53, in __getattr__
webapp_1  |     self._setup(name)
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
webapp_1  |     self._wrapped = Settings(settings_module)
webapp_1  |   File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 97, in __init__
webapp_1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
webapp_1  |   File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
webapp_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webapp_1  |   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
webapp_1  |   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
webapp_1  |   File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
webapp_1  |   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
webapp_1  |   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
webapp_1  |   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
webapp_1  |   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
webapp_1  |   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
webapp_1  |   File "<frozen importlib._bootstrap>", line 1129, in _exec
webapp_1  |   File "<frozen importlib._bootstrap>", line 1471, in exec_module
webapp_1  |   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
webapp_1  |   File "/home/peeljobs/jobsp/__init__.py", line 5, in <module>
webapp_1  |     from .celery import app as celery_app
webapp_1  |   File "/home/peeljobs/jobsp/celery.py", line 3, in <module>
webapp_1  |     from celery import Celery
webapp_1  | ImportError: No module named 'celery'
job_webapp_1 exited with code 1
```

It this project supported now?

**Comment by iColdPlayer** [comment]
@affluent-bilby-classifieds You can just comment on the `mongodb` section and it'll be fine.
I also had the same problem, after commenting on `mongodb` it solves my problem, but another problem it might come during the migration, related to this #71

**Comment by Jain-Shab** [comment]
Hello, @iColdPlayer  and @affluent-bilby-classifieds  How you resolved the issue. I am facing the same issue.

**Comment by amitieMELex** [comment]
You need to create .env file in the same folder where settings.py exist and keep all settings parameters there.
